
name: Modified Build and Test
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 21
        - 22-ea
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-build (${{ matrix.java-version }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/graphhopper/graphhopper', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: temurin
    - run: touch optcd-4.txt
    - name: Cache Maven artifacts
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |-
          ${{ runner.os }}-maven-
    - run: touch optcd-5.txt
    - name: Cache node
      uses: actions/cache@v3
      with:
        path: web-bundle/node
        key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
        restore-keys: |-
          ${{ runner.os}}-node-
    - run: touch optcd-6.txt
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: web-bundle/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml', '**/package.json')
          }}
        restore-keys: |-
          ${{ runner.os}}-node_modules-
    - run: touch optcd-7.txt
    - name: Build ${{ matrix.java-version }}
      run: mvn -B clean test
    - run: touch optcd-8.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-build (${{ matrix.java-version }})
        path: /home/runner/inotifywait-log-build (${{ matrix.java-version }}).csv
    name: build (${{ matrix.java-version }})
'on':
- push
- workflow_dispatch
